<?php
// Error reporting:
error_reporting(E_ALL^E_NOTICE);

// Including the DB connection file:
require 'connect.php';
$extension='';
$files_array = array();


/* Opening the thumbnail directory and looping through all the thumbs: */

$dir_handle = @opendir($directory) or die("There is an error with your file directory!");
while ($file = readdir($dir_handle)) 
{
	/* Skipping the system files: */
	if($file{0}=='.') continue;
	
	/* end() returns the last element of the array generated by the explode() function: */
	$parts = explode('.',$file);
	$extension = strtolower(end($parts));
	
	/* Skipping the php files: */
	if($extension == 'php') continue;

	$files_array[]=$file;
}

/* Sorting the files alphabetically */
sort($files_array,SORT_STRING);

$file_downloads=array();

$result = mysql_query("SELECT * FROM download_manager");

if(mysql_num_rows($result))
while($row=mysql_fetch_assoc($result))
{
	/* 	The key of the $file_downloads array will be the name of the file,
		and will contain the number of downloads: */
	$file_downloads[$row['filename']]=$row['downloads'];
}

?>


<!DOCTYPE html>
<html lang="en">
<?php
    include('include/header.php');
?>

<body>
<?php
   include('include/body_header.php');
?>
 
<main id="main" style="margin-top:170px;">
       <!--==========================
      Frequently Asked Questions Section
    ============================-->
    <section id="faq">
      <div class="container">
        <header class="section-header">
        <h3>ORIGINAL ARTICLES ( Drop Down 1 )</h3>
        </header>

        <ul id="faq-list" class="wow fadeInUp manager">
        <?php 

          foreach($files_array as $key=>$val)
          {
           
            echo '<li>
                    <a href="download.php?file='.urlencode($val).'">'.$val.' 
                      <span class="pull-right download-count">'.(int)$file_downloads[$val].'</span>
                    </a>
                  
                </li>';
          }
        ?>
        
        </ul>

      </div>
    </section><!-- #faq -->
    </main>
  <?php
   include('include/body_footer.php');
    
?>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->
  <?php
   include('include/footer.php');
   include('include/model.php');
?>

</body>
</html>
